# Generated by Django 5.2.11 on 2026-02-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_toy_alter_feeding_options_alter_feeding_cat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='toy',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
